apiVersion: v1
kind: Pod
metadata:
  name: my-configmap-pod1-2
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: port
          valueFrom:
            configMapKeyRef:
              name: my-config1
              key: port
