apiVersion: v1
kind: Service
metadata:
  name: utc-service                           
spec:
  type: NodePort
  selector:
    env: dev
  ports:
  - name: utrains-service-port
    protocol: TCP
    port: 80
    targetPort: 8082
    #nodePort: 30001     # 30,000-32,767