apiVersion: v1
kind: Service
metadata:
  namespace: app1
  name: app1-service
spec:
  type: LoadBalancer
  selector:
    env: qa
  ports:
  - name: utrains-service-port
    protocol: TCP
    port: 80
    targetPort: 8082